version: "3.8"
services:
  # ==================== EXTERNAL SERVICES (DOCKER) ====================
  # These services run in Docker containers
  # Your application services (order-ingress, portfolio-service, risk-service, trading-engine) run locally

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: citusdata/citus:12.1
    environment:
      POSTGRES_USER: quantis
      POSTGRES_PASSWORD: quantis
      POSTGRES_DB: quantisdb
    ports:
      - "5433:5432"

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  # ==================== DATA STORAGE SERVICES ====================
  cassandra:
    image: cassandra:4.1
    environment:
      CASSANDRA_CLUSTER_NAME: QuantisCluster
      CASSANDRA_START_RPC: "true"
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # ==================== APPLICATION SERVICES (RUN LOCALLY) ====================
  # These services are configured to run locally on your machine
  # Start them manually using: ./mvnw spring-boot:run
  #
  # order-ingress:           http://localhost:8080
  # portfolio-service:       http://localhost:8082 (HTTP), localhost:9090 (gRPC)
  # risk-service:            http://localhost:8081
  # trading-engine:          http://localhost:8083
  # market-data-service:     http://localhost:8084 (GraphQL + WebSocket + gRPC)
  # dashboard-gateway:       http://localhost:8085 (GraphQL Gateway)
  # elasticsearch-writer:   http://localhost:8086 (Elasticsearch Writer Service)
  # cassandra-writer:       http://localhost:8087 (Cassandra Writer Service)
  # postgres-writer:         http://localhost:8088 (PostgreSQL Writer Service)
  # update-service:          http://localhost:8089 (Update Service)

volumes:
  esdata:
    driver: local
  cassandra_data:
    driver: local
  # Application service logs are stored locally in services/*/logs/ directories
