version: "3.8"
services:
  # ==================== EXTERNAL SERVICES (DOCKER) ====================
  # These services run in Docker containers
  # Your application services (order-ingress, portfolio-service, risk-service, trading-engine) run locally

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: citusdata/citus:12.1
    environment:
      POSTGRES_USER: quantis
      POSTGRES_PASSWORD: quantis
      POSTGRES_DB: quantisdb
    ports:
      - "5433:5432"

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  # Optional services (commented out - uncomment if needed)
  # cassandra:
  #   image: cassandra:4.1
  #   environment:
  #     CASSANDRA_CLUSTER_NAME: QuantisCluster
  #     CASSANDRA_START_RPC: "true"
  #   ports:
  #     - "9042:9042"

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
  #   environment:
  #     - discovery.type=single-node
  #     - ES_JAVA_OPTS=-Xms512m -Xmx512m
  #     - xpack.security.enabled=false
  #     - xpack.security.http.ssl.enabled=false
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data

  # ==================== APPLICATION SERVICES (RUN LOCALLY) ====================
  # These services are configured to run locally on your machine
  # Start them manually using: ./mvnw spring-boot:run
  #
  # order-ingress:     http://localhost:8080
  # portfolio-service: http://localhost:8082 (HTTP), localhost:9090 (gRPC)
  # risk-service:      http://localhost:8081
  # trading-engine:    http://localhost:8083

volumes:
  esdata:
    driver: local
  # Application service logs are stored locally in services/*/logs/ directories
