// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

// Protobuf Java Version: 3.25.1
package com.quantis.portfolio_service.grpc;

/**
 * Protobuf type {@code com.quantis.portfolio.GetAllPositionsResponse}
 */
public final class GetAllPositionsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.quantis.portfolio.GetAllPositionsResponse)
    GetAllPositionsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAllPositionsResponse.newBuilder() to construct.
  private GetAllPositionsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAllPositionsResponse() {
    positions_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetAllPositionsResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetAllPositionsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetAllPositionsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.quantis.portfolio_service.grpc.GetAllPositionsResponse.class, com.quantis.portfolio_service.grpc.GetAllPositionsResponse.Builder.class);
  }

  public static final int POSITIONS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.quantis.portfolio_service.grpc.GetPositionResponse> positions_;
  /**
   * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.quantis.portfolio_service.grpc.GetPositionResponse> getPositionsList() {
    return positions_;
  }
  /**
   * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.quantis.portfolio_service.grpc.GetPositionResponseOrBuilder> 
      getPositionsOrBuilderList() {
    return positions_;
  }
  /**
   * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
   */
  @java.lang.Override
  public int getPositionsCount() {
    return positions_.size();
  }
  /**
   * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
   */
  @java.lang.Override
  public com.quantis.portfolio_service.grpc.GetPositionResponse getPositions(int index) {
    return positions_.get(index);
  }
  /**
   * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
   */
  @java.lang.Override
  public com.quantis.portfolio_service.grpc.GetPositionResponseOrBuilder getPositionsOrBuilder(
      int index) {
    return positions_.get(index);
  }

  public static final int TOTAL_POSITIONS_VALUE_FIELD_NUMBER = 2;
  private double totalPositionsValue_ = 0D;
  /**
   * <code>double total_positions_value = 2;</code>
   * @return The totalPositionsValue.
   */
  @java.lang.Override
  public double getTotalPositionsValue() {
    return totalPositionsValue_;
  }

  public static final int TOTAL_UNREALIZED_PNL_FIELD_NUMBER = 3;
  private double totalUnrealizedPnl_ = 0D;
  /**
   * <code>double total_unrealized_pnl = 3;</code>
   * @return The totalUnrealizedPnl.
   */
  @java.lang.Override
  public double getTotalUnrealizedPnl() {
    return totalUnrealizedPnl_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 4;
  private long timestamp_ = 0L;
  /**
   * <code>int64 timestamp = 4;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < positions_.size(); i++) {
      output.writeMessage(1, positions_.get(i));
    }
    if (java.lang.Double.doubleToRawLongBits(totalPositionsValue_) != 0) {
      output.writeDouble(2, totalPositionsValue_);
    }
    if (java.lang.Double.doubleToRawLongBits(totalUnrealizedPnl_) != 0) {
      output.writeDouble(3, totalUnrealizedPnl_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(4, timestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < positions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, positions_.get(i));
    }
    if (java.lang.Double.doubleToRawLongBits(totalPositionsValue_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, totalPositionsValue_);
    }
    if (java.lang.Double.doubleToRawLongBits(totalUnrealizedPnl_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, totalUnrealizedPnl_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, timestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.quantis.portfolio_service.grpc.GetAllPositionsResponse)) {
      return super.equals(obj);
    }
    com.quantis.portfolio_service.grpc.GetAllPositionsResponse other = (com.quantis.portfolio_service.grpc.GetAllPositionsResponse) obj;

    if (!getPositionsList()
        .equals(other.getPositionsList())) return false;
    if (java.lang.Double.doubleToLongBits(getTotalPositionsValue())
        != java.lang.Double.doubleToLongBits(
            other.getTotalPositionsValue())) return false;
    if (java.lang.Double.doubleToLongBits(getTotalUnrealizedPnl())
        != java.lang.Double.doubleToLongBits(
            other.getTotalUnrealizedPnl())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPositionsCount() > 0) {
      hash = (37 * hash) + POSITIONS_FIELD_NUMBER;
      hash = (53 * hash) + getPositionsList().hashCode();
    }
    hash = (37 * hash) + TOTAL_POSITIONS_VALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTotalPositionsValue()));
    hash = (37 * hash) + TOTAL_UNREALIZED_PNL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTotalUnrealizedPnl()));
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.quantis.portfolio_service.grpc.GetAllPositionsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.quantis.portfolio_service.grpc.GetAllPositionsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.quantis.portfolio_service.grpc.GetAllPositionsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.quantis.portfolio_service.grpc.GetAllPositionsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.quantis.portfolio_service.grpc.GetAllPositionsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.quantis.portfolio_service.grpc.GetAllPositionsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.quantis.portfolio_service.grpc.GetAllPositionsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.quantis.portfolio_service.grpc.GetAllPositionsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.quantis.portfolio_service.grpc.GetAllPositionsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.quantis.portfolio_service.grpc.GetAllPositionsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.quantis.portfolio_service.grpc.GetAllPositionsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.quantis.portfolio_service.grpc.GetAllPositionsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.quantis.portfolio_service.grpc.GetAllPositionsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.quantis.portfolio.GetAllPositionsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.quantis.portfolio.GetAllPositionsResponse)
      com.quantis.portfolio_service.grpc.GetAllPositionsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetAllPositionsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetAllPositionsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.quantis.portfolio_service.grpc.GetAllPositionsResponse.class, com.quantis.portfolio_service.grpc.GetAllPositionsResponse.Builder.class);
    }

    // Construct using com.quantis.portfolio_service.grpc.GetAllPositionsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (positionsBuilder_ == null) {
        positions_ = java.util.Collections.emptyList();
      } else {
        positions_ = null;
        positionsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      totalPositionsValue_ = 0D;
      totalUnrealizedPnl_ = 0D;
      timestamp_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetAllPositionsResponse_descriptor;
    }

    @java.lang.Override
    public com.quantis.portfolio_service.grpc.GetAllPositionsResponse getDefaultInstanceForType() {
      return com.quantis.portfolio_service.grpc.GetAllPositionsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.quantis.portfolio_service.grpc.GetAllPositionsResponse build() {
      com.quantis.portfolio_service.grpc.GetAllPositionsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.quantis.portfolio_service.grpc.GetAllPositionsResponse buildPartial() {
      com.quantis.portfolio_service.grpc.GetAllPositionsResponse result = new com.quantis.portfolio_service.grpc.GetAllPositionsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.quantis.portfolio_service.grpc.GetAllPositionsResponse result) {
      if (positionsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          positions_ = java.util.Collections.unmodifiableList(positions_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.positions_ = positions_;
      } else {
        result.positions_ = positionsBuilder_.build();
      }
    }

    private void buildPartial0(com.quantis.portfolio_service.grpc.GetAllPositionsResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.totalPositionsValue_ = totalPositionsValue_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.totalUnrealizedPnl_ = totalUnrealizedPnl_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.timestamp_ = timestamp_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.quantis.portfolio_service.grpc.GetAllPositionsResponse) {
        return mergeFrom((com.quantis.portfolio_service.grpc.GetAllPositionsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.quantis.portfolio_service.grpc.GetAllPositionsResponse other) {
      if (other == com.quantis.portfolio_service.grpc.GetAllPositionsResponse.getDefaultInstance()) return this;
      if (positionsBuilder_ == null) {
        if (!other.positions_.isEmpty()) {
          if (positions_.isEmpty()) {
            positions_ = other.positions_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePositionsIsMutable();
            positions_.addAll(other.positions_);
          }
          onChanged();
        }
      } else {
        if (!other.positions_.isEmpty()) {
          if (positionsBuilder_.isEmpty()) {
            positionsBuilder_.dispose();
            positionsBuilder_ = null;
            positions_ = other.positions_;
            bitField0_ = (bitField0_ & ~0x00000001);
            positionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPositionsFieldBuilder() : null;
          } else {
            positionsBuilder_.addAllMessages(other.positions_);
          }
        }
      }
      if (other.getTotalPositionsValue() != 0D) {
        setTotalPositionsValue(other.getTotalPositionsValue());
      }
      if (other.getTotalUnrealizedPnl() != 0D) {
        setTotalUnrealizedPnl(other.getTotalUnrealizedPnl());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.quantis.portfolio_service.grpc.GetPositionResponse m =
                  input.readMessage(
                      com.quantis.portfolio_service.grpc.GetPositionResponse.parser(),
                      extensionRegistry);
              if (positionsBuilder_ == null) {
                ensurePositionsIsMutable();
                positions_.add(m);
              } else {
                positionsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 17: {
              totalPositionsValue_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              totalUnrealizedPnl_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 32: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.quantis.portfolio_service.grpc.GetPositionResponse> positions_ =
      java.util.Collections.emptyList();
    private void ensurePositionsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        positions_ = new java.util.ArrayList<com.quantis.portfolio_service.grpc.GetPositionResponse>(positions_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.quantis.portfolio_service.grpc.GetPositionResponse, com.quantis.portfolio_service.grpc.GetPositionResponse.Builder, com.quantis.portfolio_service.grpc.GetPositionResponseOrBuilder> positionsBuilder_;

    /**
     * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
     */
    public java.util.List<com.quantis.portfolio_service.grpc.GetPositionResponse> getPositionsList() {
      if (positionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(positions_);
      } else {
        return positionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
     */
    public int getPositionsCount() {
      if (positionsBuilder_ == null) {
        return positions_.size();
      } else {
        return positionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
     */
    public com.quantis.portfolio_service.grpc.GetPositionResponse getPositions(int index) {
      if (positionsBuilder_ == null) {
        return positions_.get(index);
      } else {
        return positionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
     */
    public Builder setPositions(
        int index, com.quantis.portfolio_service.grpc.GetPositionResponse value) {
      if (positionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePositionsIsMutable();
        positions_.set(index, value);
        onChanged();
      } else {
        positionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
     */
    public Builder setPositions(
        int index, com.quantis.portfolio_service.grpc.GetPositionResponse.Builder builderForValue) {
      if (positionsBuilder_ == null) {
        ensurePositionsIsMutable();
        positions_.set(index, builderForValue.build());
        onChanged();
      } else {
        positionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
     */
    public Builder addPositions(com.quantis.portfolio_service.grpc.GetPositionResponse value) {
      if (positionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePositionsIsMutable();
        positions_.add(value);
        onChanged();
      } else {
        positionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
     */
    public Builder addPositions(
        int index, com.quantis.portfolio_service.grpc.GetPositionResponse value) {
      if (positionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePositionsIsMutable();
        positions_.add(index, value);
        onChanged();
      } else {
        positionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
     */
    public Builder addPositions(
        com.quantis.portfolio_service.grpc.GetPositionResponse.Builder builderForValue) {
      if (positionsBuilder_ == null) {
        ensurePositionsIsMutable();
        positions_.add(builderForValue.build());
        onChanged();
      } else {
        positionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
     */
    public Builder addPositions(
        int index, com.quantis.portfolio_service.grpc.GetPositionResponse.Builder builderForValue) {
      if (positionsBuilder_ == null) {
        ensurePositionsIsMutable();
        positions_.add(index, builderForValue.build());
        onChanged();
      } else {
        positionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
     */
    public Builder addAllPositions(
        java.lang.Iterable<? extends com.quantis.portfolio_service.grpc.GetPositionResponse> values) {
      if (positionsBuilder_ == null) {
        ensurePositionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, positions_);
        onChanged();
      } else {
        positionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
     */
    public Builder clearPositions() {
      if (positionsBuilder_ == null) {
        positions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        positionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
     */
    public Builder removePositions(int index) {
      if (positionsBuilder_ == null) {
        ensurePositionsIsMutable();
        positions_.remove(index);
        onChanged();
      } else {
        positionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
     */
    public com.quantis.portfolio_service.grpc.GetPositionResponse.Builder getPositionsBuilder(
        int index) {
      return getPositionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
     */
    public com.quantis.portfolio_service.grpc.GetPositionResponseOrBuilder getPositionsOrBuilder(
        int index) {
      if (positionsBuilder_ == null) {
        return positions_.get(index);  } else {
        return positionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
     */
    public java.util.List<? extends com.quantis.portfolio_service.grpc.GetPositionResponseOrBuilder> 
         getPositionsOrBuilderList() {
      if (positionsBuilder_ != null) {
        return positionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(positions_);
      }
    }
    /**
     * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
     */
    public com.quantis.portfolio_service.grpc.GetPositionResponse.Builder addPositionsBuilder() {
      return getPositionsFieldBuilder().addBuilder(
          com.quantis.portfolio_service.grpc.GetPositionResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
     */
    public com.quantis.portfolio_service.grpc.GetPositionResponse.Builder addPositionsBuilder(
        int index) {
      return getPositionsFieldBuilder().addBuilder(
          index, com.quantis.portfolio_service.grpc.GetPositionResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
     */
    public java.util.List<com.quantis.portfolio_service.grpc.GetPositionResponse.Builder> 
         getPositionsBuilderList() {
      return getPositionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.quantis.portfolio_service.grpc.GetPositionResponse, com.quantis.portfolio_service.grpc.GetPositionResponse.Builder, com.quantis.portfolio_service.grpc.GetPositionResponseOrBuilder> 
        getPositionsFieldBuilder() {
      if (positionsBuilder_ == null) {
        positionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.quantis.portfolio_service.grpc.GetPositionResponse, com.quantis.portfolio_service.grpc.GetPositionResponse.Builder, com.quantis.portfolio_service.grpc.GetPositionResponseOrBuilder>(
                positions_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        positions_ = null;
      }
      return positionsBuilder_;
    }

    private double totalPositionsValue_ ;
    /**
     * <code>double total_positions_value = 2;</code>
     * @return The totalPositionsValue.
     */
    @java.lang.Override
    public double getTotalPositionsValue() {
      return totalPositionsValue_;
    }
    /**
     * <code>double total_positions_value = 2;</code>
     * @param value The totalPositionsValue to set.
     * @return This builder for chaining.
     */
    public Builder setTotalPositionsValue(double value) {

      totalPositionsValue_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double total_positions_value = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalPositionsValue() {
      bitField0_ = (bitField0_ & ~0x00000002);
      totalPositionsValue_ = 0D;
      onChanged();
      return this;
    }

    private double totalUnrealizedPnl_ ;
    /**
     * <code>double total_unrealized_pnl = 3;</code>
     * @return The totalUnrealizedPnl.
     */
    @java.lang.Override
    public double getTotalUnrealizedPnl() {
      return totalUnrealizedPnl_;
    }
    /**
     * <code>double total_unrealized_pnl = 3;</code>
     * @param value The totalUnrealizedPnl to set.
     * @return This builder for chaining.
     */
    public Builder setTotalUnrealizedPnl(double value) {

      totalUnrealizedPnl_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double total_unrealized_pnl = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalUnrealizedPnl() {
      bitField0_ = (bitField0_ & ~0x00000004);
      totalUnrealizedPnl_ = 0D;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 4;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 4;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000008);
      timestamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.quantis.portfolio.GetAllPositionsResponse)
  }

  // @@protoc_insertion_point(class_scope:com.quantis.portfolio.GetAllPositionsResponse)
  private static final com.quantis.portfolio_service.grpc.GetAllPositionsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.quantis.portfolio_service.grpc.GetAllPositionsResponse();
  }

  public static com.quantis.portfolio_service.grpc.GetAllPositionsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAllPositionsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAllPositionsResponse>() {
    @java.lang.Override
    public GetAllPositionsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetAllPositionsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAllPositionsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.quantis.portfolio_service.grpc.GetAllPositionsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

