// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

// Protobuf Java Version: 3.25.1
package com.quantis.portfolio_service.grpc;

public interface GetPositionValueResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.quantis.portfolio.GetPositionValueResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double position_value = 1;</code>
   * @return The positionValue.
   */
  double getPositionValue();

  /**
   * <code>double quantity = 2;</code>
   * @return The quantity.
   */
  double getQuantity();

  /**
   * <code>double average_price = 3;</code>
   * @return The averagePrice.
   */
  double getAveragePrice();

  /**
   * <code>double current_price = 4;</code>
   * @return The currentPrice.
   */
  double getCurrentPrice();

  /**
   * <code>double unrealized_pnl = 5;</code>
   * @return The unrealizedPnl.
   */
  double getUnrealizedPnl();

  /**
   * <code>string symbol = 6;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 6;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
