// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

// Protobuf Java Version: 3.25.1
package com.quantis.portfolio_service.grpc;

/**
 * Protobuf type {@code com.quantis.portfolio.GetPositionValueResponse}
 */
public final class GetPositionValueResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.quantis.portfolio.GetPositionValueResponse)
    GetPositionValueResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetPositionValueResponse.newBuilder() to construct.
  private GetPositionValueResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetPositionValueResponse() {
    symbol_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetPositionValueResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetPositionValueResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetPositionValueResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.quantis.portfolio_service.grpc.GetPositionValueResponse.class, com.quantis.portfolio_service.grpc.GetPositionValueResponse.Builder.class);
  }

  public static final int POSITION_VALUE_FIELD_NUMBER = 1;
  private double positionValue_ = 0D;
  /**
   * <code>double position_value = 1;</code>
   * @return The positionValue.
   */
  @java.lang.Override
  public double getPositionValue() {
    return positionValue_;
  }

  public static final int QUANTITY_FIELD_NUMBER = 2;
  private double quantity_ = 0D;
  /**
   * <code>double quantity = 2;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public double getQuantity() {
    return quantity_;
  }

  public static final int AVERAGE_PRICE_FIELD_NUMBER = 3;
  private double averagePrice_ = 0D;
  /**
   * <code>double average_price = 3;</code>
   * @return The averagePrice.
   */
  @java.lang.Override
  public double getAveragePrice() {
    return averagePrice_;
  }

  public static final int CURRENT_PRICE_FIELD_NUMBER = 4;
  private double currentPrice_ = 0D;
  /**
   * <code>double current_price = 4;</code>
   * @return The currentPrice.
   */
  @java.lang.Override
  public double getCurrentPrice() {
    return currentPrice_;
  }

  public static final int UNREALIZED_PNL_FIELD_NUMBER = 5;
  private double unrealizedPnl_ = 0D;
  /**
   * <code>double unrealized_pnl = 5;</code>
   * @return The unrealizedPnl.
   */
  @java.lang.Override
  public double getUnrealizedPnl() {
    return unrealizedPnl_;
  }

  public static final int SYMBOL_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object symbol_ = "";
  /**
   * <code>string symbol = 6;</code>
   * @return The symbol.
   */
  @java.lang.Override
  public java.lang.String getSymbol() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <code>string symbol = 6;</code>
   * @return The bytes for symbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 7;
  private long timestamp_ = 0L;
  /**
   * <code>int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(positionValue_) != 0) {
      output.writeDouble(1, positionValue_);
    }
    if (java.lang.Double.doubleToRawLongBits(quantity_) != 0) {
      output.writeDouble(2, quantity_);
    }
    if (java.lang.Double.doubleToRawLongBits(averagePrice_) != 0) {
      output.writeDouble(3, averagePrice_);
    }
    if (java.lang.Double.doubleToRawLongBits(currentPrice_) != 0) {
      output.writeDouble(4, currentPrice_);
    }
    if (java.lang.Double.doubleToRawLongBits(unrealizedPnl_) != 0) {
      output.writeDouble(5, unrealizedPnl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(symbol_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, symbol_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(7, timestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(positionValue_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, positionValue_);
    }
    if (java.lang.Double.doubleToRawLongBits(quantity_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, quantity_);
    }
    if (java.lang.Double.doubleToRawLongBits(averagePrice_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, averagePrice_);
    }
    if (java.lang.Double.doubleToRawLongBits(currentPrice_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, currentPrice_);
    }
    if (java.lang.Double.doubleToRawLongBits(unrealizedPnl_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, unrealizedPnl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(symbol_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, symbol_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, timestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.quantis.portfolio_service.grpc.GetPositionValueResponse)) {
      return super.equals(obj);
    }
    com.quantis.portfolio_service.grpc.GetPositionValueResponse other = (com.quantis.portfolio_service.grpc.GetPositionValueResponse) obj;

    if (java.lang.Double.doubleToLongBits(getPositionValue())
        != java.lang.Double.doubleToLongBits(
            other.getPositionValue())) return false;
    if (java.lang.Double.doubleToLongBits(getQuantity())
        != java.lang.Double.doubleToLongBits(
            other.getQuantity())) return false;
    if (java.lang.Double.doubleToLongBits(getAveragePrice())
        != java.lang.Double.doubleToLongBits(
            other.getAveragePrice())) return false;
    if (java.lang.Double.doubleToLongBits(getCurrentPrice())
        != java.lang.Double.doubleToLongBits(
            other.getCurrentPrice())) return false;
    if (java.lang.Double.doubleToLongBits(getUnrealizedPnl())
        != java.lang.Double.doubleToLongBits(
            other.getUnrealizedPnl())) return false;
    if (!getSymbol()
        .equals(other.getSymbol())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + POSITION_VALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPositionValue()));
    hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getQuantity()));
    hash = (37 * hash) + AVERAGE_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAveragePrice()));
    hash = (37 * hash) + CURRENT_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCurrentPrice()));
    hash = (37 * hash) + UNREALIZED_PNL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getUnrealizedPnl()));
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.quantis.portfolio_service.grpc.GetPositionValueResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.quantis.portfolio_service.grpc.GetPositionValueResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.quantis.portfolio_service.grpc.GetPositionValueResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.quantis.portfolio_service.grpc.GetPositionValueResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.quantis.portfolio_service.grpc.GetPositionValueResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.quantis.portfolio_service.grpc.GetPositionValueResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.quantis.portfolio_service.grpc.GetPositionValueResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.quantis.portfolio_service.grpc.GetPositionValueResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.quantis.portfolio_service.grpc.GetPositionValueResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.quantis.portfolio_service.grpc.GetPositionValueResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.quantis.portfolio_service.grpc.GetPositionValueResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.quantis.portfolio_service.grpc.GetPositionValueResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.quantis.portfolio_service.grpc.GetPositionValueResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.quantis.portfolio.GetPositionValueResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.quantis.portfolio.GetPositionValueResponse)
      com.quantis.portfolio_service.grpc.GetPositionValueResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetPositionValueResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetPositionValueResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.quantis.portfolio_service.grpc.GetPositionValueResponse.class, com.quantis.portfolio_service.grpc.GetPositionValueResponse.Builder.class);
    }

    // Construct using com.quantis.portfolio_service.grpc.GetPositionValueResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      positionValue_ = 0D;
      quantity_ = 0D;
      averagePrice_ = 0D;
      currentPrice_ = 0D;
      unrealizedPnl_ = 0D;
      symbol_ = "";
      timestamp_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetPositionValueResponse_descriptor;
    }

    @java.lang.Override
    public com.quantis.portfolio_service.grpc.GetPositionValueResponse getDefaultInstanceForType() {
      return com.quantis.portfolio_service.grpc.GetPositionValueResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.quantis.portfolio_service.grpc.GetPositionValueResponse build() {
      com.quantis.portfolio_service.grpc.GetPositionValueResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.quantis.portfolio_service.grpc.GetPositionValueResponse buildPartial() {
      com.quantis.portfolio_service.grpc.GetPositionValueResponse result = new com.quantis.portfolio_service.grpc.GetPositionValueResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.quantis.portfolio_service.grpc.GetPositionValueResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.positionValue_ = positionValue_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.quantity_ = quantity_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.averagePrice_ = averagePrice_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.currentPrice_ = currentPrice_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.unrealizedPnl_ = unrealizedPnl_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.symbol_ = symbol_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.timestamp_ = timestamp_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.quantis.portfolio_service.grpc.GetPositionValueResponse) {
        return mergeFrom((com.quantis.portfolio_service.grpc.GetPositionValueResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.quantis.portfolio_service.grpc.GetPositionValueResponse other) {
      if (other == com.quantis.portfolio_service.grpc.GetPositionValueResponse.getDefaultInstance()) return this;
      if (other.getPositionValue() != 0D) {
        setPositionValue(other.getPositionValue());
      }
      if (other.getQuantity() != 0D) {
        setQuantity(other.getQuantity());
      }
      if (other.getAveragePrice() != 0D) {
        setAveragePrice(other.getAveragePrice());
      }
      if (other.getCurrentPrice() != 0D) {
        setCurrentPrice(other.getCurrentPrice());
      }
      if (other.getUnrealizedPnl() != 0D) {
        setUnrealizedPnl(other.getUnrealizedPnl());
      }
      if (!other.getSymbol().isEmpty()) {
        symbol_ = other.symbol_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              positionValue_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 17: {
              quantity_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              averagePrice_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              currentPrice_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 41: {
              unrealizedPnl_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 50: {
              symbol_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double positionValue_ ;
    /**
     * <code>double position_value = 1;</code>
     * @return The positionValue.
     */
    @java.lang.Override
    public double getPositionValue() {
      return positionValue_;
    }
    /**
     * <code>double position_value = 1;</code>
     * @param value The positionValue to set.
     * @return This builder for chaining.
     */
    public Builder setPositionValue(double value) {

      positionValue_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>double position_value = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPositionValue() {
      bitField0_ = (bitField0_ & ~0x00000001);
      positionValue_ = 0D;
      onChanged();
      return this;
    }

    private double quantity_ ;
    /**
     * <code>double quantity = 2;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public double getQuantity() {
      return quantity_;
    }
    /**
     * <code>double quantity = 2;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(double value) {

      quantity_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double quantity = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      bitField0_ = (bitField0_ & ~0x00000002);
      quantity_ = 0D;
      onChanged();
      return this;
    }

    private double averagePrice_ ;
    /**
     * <code>double average_price = 3;</code>
     * @return The averagePrice.
     */
    @java.lang.Override
    public double getAveragePrice() {
      return averagePrice_;
    }
    /**
     * <code>double average_price = 3;</code>
     * @param value The averagePrice to set.
     * @return This builder for chaining.
     */
    public Builder setAveragePrice(double value) {

      averagePrice_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double average_price = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAveragePrice() {
      bitField0_ = (bitField0_ & ~0x00000004);
      averagePrice_ = 0D;
      onChanged();
      return this;
    }

    private double currentPrice_ ;
    /**
     * <code>double current_price = 4;</code>
     * @return The currentPrice.
     */
    @java.lang.Override
    public double getCurrentPrice() {
      return currentPrice_;
    }
    /**
     * <code>double current_price = 4;</code>
     * @param value The currentPrice to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentPrice(double value) {

      currentPrice_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>double current_price = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentPrice() {
      bitField0_ = (bitField0_ & ~0x00000008);
      currentPrice_ = 0D;
      onChanged();
      return this;
    }

    private double unrealizedPnl_ ;
    /**
     * <code>double unrealized_pnl = 5;</code>
     * @return The unrealizedPnl.
     */
    @java.lang.Override
    public double getUnrealizedPnl() {
      return unrealizedPnl_;
    }
    /**
     * <code>double unrealized_pnl = 5;</code>
     * @param value The unrealizedPnl to set.
     * @return This builder for chaining.
     */
    public Builder setUnrealizedPnl(double value) {

      unrealizedPnl_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>double unrealized_pnl = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnrealizedPnl() {
      bitField0_ = (bitField0_ & ~0x00000010);
      unrealizedPnl_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object symbol_ = "";
    /**
     * <code>string symbol = 6;</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string symbol = 6;</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string symbol = 6;</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      symbol_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      symbol_ = getDefaultInstance().getSymbol();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 6;</code>
     * @param value The bytes for symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      symbol_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 7;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 7;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000040);
      timestamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.quantis.portfolio.GetPositionValueResponse)
  }

  // @@protoc_insertion_point(class_scope:com.quantis.portfolio.GetPositionValueResponse)
  private static final com.quantis.portfolio_service.grpc.GetPositionValueResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.quantis.portfolio_service.grpc.GetPositionValueResponse();
  }

  public static com.quantis.portfolio_service.grpc.GetPositionValueResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetPositionValueResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetPositionValueResponse>() {
    @java.lang.Override
    public GetPositionValueResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetPositionValueResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetPositionValueResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.quantis.portfolio_service.grpc.GetPositionValueResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

