// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

// Protobuf Java Version: 3.25.1
package com.quantis.portfolio_service.grpc;

public interface GetPositionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.quantis.portfolio.GetPositionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string symbol = 2;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 2;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>double quantity = 3;</code>
   * @return The quantity.
   */
  double getQuantity();

  /**
   * <code>double average_price = 4;</code>
   * @return The averagePrice.
   */
  double getAveragePrice();

  /**
   * <code>double current_price = 5;</code>
   * @return The currentPrice.
   */
  double getCurrentPrice();

  /**
   * <code>double market_value = 6;</code>
   * @return The marketValue.
   */
  double getMarketValue();

  /**
   * <code>double unrealized_pnl = 7;</code>
   * @return The unrealizedPnl.
   */
  double getUnrealizedPnl();

  /**
   * <code>int64 last_updated = 8;</code>
   * @return The lastUpdated.
   */
  long getLastUpdated();
}
