// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

// Protobuf Java Version: 3.25.1
package com.quantis.portfolio_service.grpc;

public interface GetTradingHistoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.quantis.portfolio.GetTradingHistoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>int32 limit = 2;</code>
   * @return The limit.
   */
  int getLimit();

  /**
   * <code>int64 start_timestamp = 3;</code>
   * @return The startTimestamp.
   */
  long getStartTimestamp();

  /**
   * <code>int64 end_timestamp = 4;</code>
   * @return The endTimestamp.
   */
  long getEndTimestamp();
}
