// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

// Protobuf Java Version: 3.25.1
package com.quantis.portfolio_service.grpc;

public interface UpdatePositionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.quantis.portfolio.UpdatePositionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string symbol = 2;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 2;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <pre>
   * positive for buy, negative for sell
   * </pre>
   *
   * <code>double quantity_change = 3;</code>
   * @return The quantityChange.
   */
  double getQuantityChange();

  /**
   * <code>double price = 4;</code>
   * @return The price.
   */
  double getPrice();

  /**
   * <pre>
   * BUY or SELL
   * </pre>
   *
   * <code>string side = 5;</code>
   * @return The side.
   */
  java.lang.String getSide();
  /**
   * <pre>
   * BUY or SELL
   * </pre>
   *
   * <code>string side = 5;</code>
   * @return The bytes for side.
   */
  com.google.protobuf.ByteString
      getSideBytes();

  /**
   * <code>string order_id = 6;</code>
   * @return The orderId.
   */
  java.lang.String getOrderId();
  /**
   * <code>string order_id = 6;</code>
   * @return The bytes for orderId.
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();
}
