// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

// Protobuf Java Version: 3.25.1
package com.quantis.portfolio_service.grpc;

public interface UpdatePositionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.quantis.portfolio.UpdatePositionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.com.quantis.portfolio.GetPositionResponse updated_position = 3;</code>
   * @return Whether the updatedPosition field is set.
   */
  boolean hasUpdatedPosition();
  /**
   * <code>.com.quantis.portfolio.GetPositionResponse updated_position = 3;</code>
   * @return The updatedPosition.
   */
  com.quantis.portfolio_service.grpc.GetPositionResponse getUpdatedPosition();
  /**
   * <code>.com.quantis.portfolio.GetPositionResponse updated_position = 3;</code>
   */
  com.quantis.portfolio_service.grpc.GetPositionResponseOrBuilder getUpdatedPositionOrBuilder();
}
