apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-ingress
  namespace: quantis-trading
  labels:
    app: order-ingress
    component: core
spec:
  replicas: 4
  selector:
    matchLabels:
      app: order-ingress
  template:
    metadata:
      labels:
        app: order-ingress
        component: core
    spec:
      containers:
        - name: order-ingress
          image: quantis/order-ingress:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: DATABASE_URL
              value: "jdbc:postgresql://postgres-service:5432/quantisdb"
            - name: REDIS_URL
              value: "redis://redis-service:6379"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
          envFrom:
            - configMapRef:
                name: quantis-config
            - secretRef:
                name: quantis-secrets
          resources:
            requests:
              cpu: 400m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: order-ingress
  namespace: quantis-trading
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: order-ingress
