apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-service
  namespace: quantis-trading
  labels:
    app: risk-service
    component: risk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: risk-service
  template:
    metadata:
      labels:
        app: risk-service
        component: risk
    spec:
      containers:
        - name: risk-service
          image: quantis/risk-service:latest
          ports:
            - containerPort: 8081
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: DATABASE_URL
              value: "jdbc:postgresql://postgres-service:5432/quantisdb"
            - name: REDIS_URL
              value: "redis://redis-service:6379"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
          envFrom:
            - configMapRef:
                name: quantis-config
            - secretRef:
                name: quantis-secrets
          resources:
            requests:
              cpu: 300m
              memory: 1Gi
            limits:
              cpu: 1500m
              memory: 3Gi
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: risk-service
  namespace: quantis-trading
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: risk-service
