apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-engine
  namespace: quantis-trading
  labels:
    app: trading-engine
    component: core
spec:
  replicas: 3 # Run 3 instances for high availability
  selector:
    matchLabels:
      app: trading-engine
  template:
    metadata:
      labels:
        app: trading-engine
        component: core
    spec:
      containers:
        - name: trading-engine
          image: quantis/trading-engine:latest
          ports:
            - containerPort: 8083
              name: http
            - containerPort: 9090
              name: grpc
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: DATABASE_URL
              value: "jdbc:postgresql://postgres-service:5432/quantisdb"
            - name: REDIS_URL
              value: "redis://redis-service:6379"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
          envFrom:
            - configMapRef:
                name: quantis-config
            - secretRef:
                name: quantis-secrets
          resources:
            requests:
              cpu: 500m # 0.5 CPU cores
              memory: 1Gi # 1GB RAM
            limits:
              cpu: 2000m # 2 CPU cores max
              memory: 4Gi # 4GB RAM max
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          # Security context
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      # Pod security
      securityContext:
        fsGroup: 1001
      # Anti-affinity: Spread across nodes
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - trading-engine
                topologyKey: kubernetes.io/hostname
