services:
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: quantis-jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--httpPort=8080 --prefix=/jenkins
      - JAVA_OPTS=-Xmx2048m -Xms1024m -Djenkins.install.runSetupWizard=false
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin123
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ../..:/workspace
      - ./plugins.txt:/usr/share/jenkins/ref/plugins.txt
      - ./init.groovy:/usr/share/jenkins/ref/init.groovy.d/init.groovy
    networks:
      - quantis-network
    user: root
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/login"]
      interval: 30s
      timeout: 10s
      retries: 5

  jenkins-agent:
    image: jenkins/inbound-agent:latest
    container_name: quantis-jenkins-agent
    restart: unless-stopped
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_SECRET=${JENKINS_AGENT_SECRET}
      - JENKINS_AGENT_NAME=quantis-agent
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ../..:/workspace
    networks:
      - quantis-network
    depends_on:
      - jenkins

volumes:
  jenkins_home:
    driver: local

networks:
  quantis-network:
    external: true
