// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

// Protobuf Java Version: 3.25.1
package com.quantis.portfolio_service.grpc;

public interface GetAllPositionsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.quantis.portfolio.GetAllPositionsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
   */
  java.util.List<com.quantis.portfolio_service.grpc.GetPositionResponse> 
      getPositionsList();
  /**
   * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
   */
  com.quantis.portfolio_service.grpc.GetPositionResponse getPositions(int index);
  /**
   * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
   */
  int getPositionsCount();
  /**
   * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
   */
  java.util.List<? extends com.quantis.portfolio_service.grpc.GetPositionResponseOrBuilder> 
      getPositionsOrBuilderList();
  /**
   * <code>repeated .com.quantis.portfolio.GetPositionResponse positions = 1;</code>
   */
  com.quantis.portfolio_service.grpc.GetPositionResponseOrBuilder getPositionsOrBuilder(
      int index);

  /**
   * <code>double total_positions_value = 2;</code>
   * @return The totalPositionsValue.
   */
  double getTotalPositionsValue();

  /**
   * <code>double total_unrealized_pnl = 3;</code>
   * @return The totalUnrealizedPnl.
   */
  double getTotalUnrealizedPnl();

  /**
   * <code>int64 timestamp = 4;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
