// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

// Protobuf Java Version: 3.25.1
package com.quantis.portfolio_service.grpc;

public interface GetCashBalanceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.quantis.portfolio.GetCashBalanceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double cash_balance = 1;</code>
   * @return The cashBalance.
   */
  double getCashBalance();

  /**
   * <code>string currency = 2;</code>
   * @return The currency.
   */
  java.lang.String getCurrency();
  /**
   * <code>string currency = 2;</code>
   * @return The bytes for currency.
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();

  /**
   * <code>int64 timestamp = 3;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
