// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

// Protobuf Java Version: 3.25.1
package com.quantis.portfolio_service.grpc;

/**
 * Protobuf type {@code com.quantis.portfolio.GetPositionResponse}
 */
public final class GetPositionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.quantis.portfolio.GetPositionResponse)
    GetPositionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetPositionResponse.newBuilder() to construct.
  private GetPositionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetPositionResponse() {
    userId_ = "";
    symbol_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetPositionResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetPositionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetPositionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.quantis.portfolio_service.grpc.GetPositionResponse.class, com.quantis.portfolio_service.grpc.GetPositionResponse.Builder.class);
  }

  public static final int USER_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object userId_ = "";
  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYMBOL_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object symbol_ = "";
  /**
   * <code>string symbol = 2;</code>
   * @return The symbol.
   */
  @java.lang.Override
  public java.lang.String getSymbol() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <code>string symbol = 2;</code>
   * @return The bytes for symbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUANTITY_FIELD_NUMBER = 3;
  private double quantity_ = 0D;
  /**
   * <code>double quantity = 3;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public double getQuantity() {
    return quantity_;
  }

  public static final int AVERAGE_PRICE_FIELD_NUMBER = 4;
  private double averagePrice_ = 0D;
  /**
   * <code>double average_price = 4;</code>
   * @return The averagePrice.
   */
  @java.lang.Override
  public double getAveragePrice() {
    return averagePrice_;
  }

  public static final int CURRENT_PRICE_FIELD_NUMBER = 5;
  private double currentPrice_ = 0D;
  /**
   * <code>double current_price = 5;</code>
   * @return The currentPrice.
   */
  @java.lang.Override
  public double getCurrentPrice() {
    return currentPrice_;
  }

  public static final int MARKET_VALUE_FIELD_NUMBER = 6;
  private double marketValue_ = 0D;
  /**
   * <code>double market_value = 6;</code>
   * @return The marketValue.
   */
  @java.lang.Override
  public double getMarketValue() {
    return marketValue_;
  }

  public static final int UNREALIZED_PNL_FIELD_NUMBER = 7;
  private double unrealizedPnl_ = 0D;
  /**
   * <code>double unrealized_pnl = 7;</code>
   * @return The unrealizedPnl.
   */
  @java.lang.Override
  public double getUnrealizedPnl() {
    return unrealizedPnl_;
  }

  public static final int LAST_UPDATED_FIELD_NUMBER = 8;
  private long lastUpdated_ = 0L;
  /**
   * <code>int64 last_updated = 8;</code>
   * @return The lastUpdated.
   */
  @java.lang.Override
  public long getLastUpdated() {
    return lastUpdated_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(symbol_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, symbol_);
    }
    if (java.lang.Double.doubleToRawLongBits(quantity_) != 0) {
      output.writeDouble(3, quantity_);
    }
    if (java.lang.Double.doubleToRawLongBits(averagePrice_) != 0) {
      output.writeDouble(4, averagePrice_);
    }
    if (java.lang.Double.doubleToRawLongBits(currentPrice_) != 0) {
      output.writeDouble(5, currentPrice_);
    }
    if (java.lang.Double.doubleToRawLongBits(marketValue_) != 0) {
      output.writeDouble(6, marketValue_);
    }
    if (java.lang.Double.doubleToRawLongBits(unrealizedPnl_) != 0) {
      output.writeDouble(7, unrealizedPnl_);
    }
    if (lastUpdated_ != 0L) {
      output.writeInt64(8, lastUpdated_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(symbol_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, symbol_);
    }
    if (java.lang.Double.doubleToRawLongBits(quantity_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, quantity_);
    }
    if (java.lang.Double.doubleToRawLongBits(averagePrice_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, averagePrice_);
    }
    if (java.lang.Double.doubleToRawLongBits(currentPrice_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, currentPrice_);
    }
    if (java.lang.Double.doubleToRawLongBits(marketValue_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, marketValue_);
    }
    if (java.lang.Double.doubleToRawLongBits(unrealizedPnl_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, unrealizedPnl_);
    }
    if (lastUpdated_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, lastUpdated_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.quantis.portfolio_service.grpc.GetPositionResponse)) {
      return super.equals(obj);
    }
    com.quantis.portfolio_service.grpc.GetPositionResponse other = (com.quantis.portfolio_service.grpc.GetPositionResponse) obj;

    if (!getUserId()
        .equals(other.getUserId())) return false;
    if (!getSymbol()
        .equals(other.getSymbol())) return false;
    if (java.lang.Double.doubleToLongBits(getQuantity())
        != java.lang.Double.doubleToLongBits(
            other.getQuantity())) return false;
    if (java.lang.Double.doubleToLongBits(getAveragePrice())
        != java.lang.Double.doubleToLongBits(
            other.getAveragePrice())) return false;
    if (java.lang.Double.doubleToLongBits(getCurrentPrice())
        != java.lang.Double.doubleToLongBits(
            other.getCurrentPrice())) return false;
    if (java.lang.Double.doubleToLongBits(getMarketValue())
        != java.lang.Double.doubleToLongBits(
            other.getMarketValue())) return false;
    if (java.lang.Double.doubleToLongBits(getUnrealizedPnl())
        != java.lang.Double.doubleToLongBits(
            other.getUnrealizedPnl())) return false;
    if (getLastUpdated()
        != other.getLastUpdated()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol().hashCode();
    hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getQuantity()));
    hash = (37 * hash) + AVERAGE_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAveragePrice()));
    hash = (37 * hash) + CURRENT_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCurrentPrice()));
    hash = (37 * hash) + MARKET_VALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMarketValue()));
    hash = (37 * hash) + UNREALIZED_PNL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getUnrealizedPnl()));
    hash = (37 * hash) + LAST_UPDATED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastUpdated());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.quantis.portfolio_service.grpc.GetPositionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.quantis.portfolio_service.grpc.GetPositionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.quantis.portfolio_service.grpc.GetPositionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.quantis.portfolio_service.grpc.GetPositionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.quantis.portfolio_service.grpc.GetPositionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.quantis.portfolio_service.grpc.GetPositionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.quantis.portfolio_service.grpc.GetPositionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.quantis.portfolio_service.grpc.GetPositionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.quantis.portfolio_service.grpc.GetPositionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.quantis.portfolio_service.grpc.GetPositionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.quantis.portfolio_service.grpc.GetPositionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.quantis.portfolio_service.grpc.GetPositionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.quantis.portfolio_service.grpc.GetPositionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.quantis.portfolio.GetPositionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.quantis.portfolio.GetPositionResponse)
      com.quantis.portfolio_service.grpc.GetPositionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetPositionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetPositionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.quantis.portfolio_service.grpc.GetPositionResponse.class, com.quantis.portfolio_service.grpc.GetPositionResponse.Builder.class);
    }

    // Construct using com.quantis.portfolio_service.grpc.GetPositionResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userId_ = "";
      symbol_ = "";
      quantity_ = 0D;
      averagePrice_ = 0D;
      currentPrice_ = 0D;
      marketValue_ = 0D;
      unrealizedPnl_ = 0D;
      lastUpdated_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetPositionResponse_descriptor;
    }

    @java.lang.Override
    public com.quantis.portfolio_service.grpc.GetPositionResponse getDefaultInstanceForType() {
      return com.quantis.portfolio_service.grpc.GetPositionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.quantis.portfolio_service.grpc.GetPositionResponse build() {
      com.quantis.portfolio_service.grpc.GetPositionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.quantis.portfolio_service.grpc.GetPositionResponse buildPartial() {
      com.quantis.portfolio_service.grpc.GetPositionResponse result = new com.quantis.portfolio_service.grpc.GetPositionResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.quantis.portfolio_service.grpc.GetPositionResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.symbol_ = symbol_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.quantity_ = quantity_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.averagePrice_ = averagePrice_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.currentPrice_ = currentPrice_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.marketValue_ = marketValue_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.unrealizedPnl_ = unrealizedPnl_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.lastUpdated_ = lastUpdated_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.quantis.portfolio_service.grpc.GetPositionResponse) {
        return mergeFrom((com.quantis.portfolio_service.grpc.GetPositionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.quantis.portfolio_service.grpc.GetPositionResponse other) {
      if (other == com.quantis.portfolio_service.grpc.GetPositionResponse.getDefaultInstance()) return this;
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getSymbol().isEmpty()) {
        symbol_ = other.symbol_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getQuantity() != 0D) {
        setQuantity(other.getQuantity());
      }
      if (other.getAveragePrice() != 0D) {
        setAveragePrice(other.getAveragePrice());
      }
      if (other.getCurrentPrice() != 0D) {
        setCurrentPrice(other.getCurrentPrice());
      }
      if (other.getMarketValue() != 0D) {
        setMarketValue(other.getMarketValue());
      }
      if (other.getUnrealizedPnl() != 0D) {
        setUnrealizedPnl(other.getUnrealizedPnl());
      }
      if (other.getLastUpdated() != 0L) {
        setLastUpdated(other.getLastUpdated());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              userId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              symbol_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 25: {
              quantity_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              averagePrice_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 41: {
              currentPrice_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 49: {
              marketValue_ = input.readDouble();
              bitField0_ |= 0x00000020;
              break;
            } // case 49
            case 57: {
              unrealizedPnl_ = input.readDouble();
              bitField0_ |= 0x00000040;
              break;
            } // case 57
            case 64: {
              lastUpdated_ = input.readInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object userId_ = "";
    /**
     * <code>string user_id = 1;</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string user_id = 1;</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user_id = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string user_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      userId_ = getDefaultInstance().getUserId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string user_id = 1;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object symbol_ = "";
    /**
     * <code>string symbol = 2;</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string symbol = 2;</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string symbol = 2;</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      symbol_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      symbol_ = getDefaultInstance().getSymbol();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 2;</code>
     * @param value The bytes for symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      symbol_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private double quantity_ ;
    /**
     * <code>double quantity = 3;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public double getQuantity() {
      return quantity_;
    }
    /**
     * <code>double quantity = 3;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(double value) {

      quantity_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double quantity = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      bitField0_ = (bitField0_ & ~0x00000004);
      quantity_ = 0D;
      onChanged();
      return this;
    }

    private double averagePrice_ ;
    /**
     * <code>double average_price = 4;</code>
     * @return The averagePrice.
     */
    @java.lang.Override
    public double getAveragePrice() {
      return averagePrice_;
    }
    /**
     * <code>double average_price = 4;</code>
     * @param value The averagePrice to set.
     * @return This builder for chaining.
     */
    public Builder setAveragePrice(double value) {

      averagePrice_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>double average_price = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAveragePrice() {
      bitField0_ = (bitField0_ & ~0x00000008);
      averagePrice_ = 0D;
      onChanged();
      return this;
    }

    private double currentPrice_ ;
    /**
     * <code>double current_price = 5;</code>
     * @return The currentPrice.
     */
    @java.lang.Override
    public double getCurrentPrice() {
      return currentPrice_;
    }
    /**
     * <code>double current_price = 5;</code>
     * @param value The currentPrice to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentPrice(double value) {

      currentPrice_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>double current_price = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentPrice() {
      bitField0_ = (bitField0_ & ~0x00000010);
      currentPrice_ = 0D;
      onChanged();
      return this;
    }

    private double marketValue_ ;
    /**
     * <code>double market_value = 6;</code>
     * @return The marketValue.
     */
    @java.lang.Override
    public double getMarketValue() {
      return marketValue_;
    }
    /**
     * <code>double market_value = 6;</code>
     * @param value The marketValue to set.
     * @return This builder for chaining.
     */
    public Builder setMarketValue(double value) {

      marketValue_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>double market_value = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMarketValue() {
      bitField0_ = (bitField0_ & ~0x00000020);
      marketValue_ = 0D;
      onChanged();
      return this;
    }

    private double unrealizedPnl_ ;
    /**
     * <code>double unrealized_pnl = 7;</code>
     * @return The unrealizedPnl.
     */
    @java.lang.Override
    public double getUnrealizedPnl() {
      return unrealizedPnl_;
    }
    /**
     * <code>double unrealized_pnl = 7;</code>
     * @param value The unrealizedPnl to set.
     * @return This builder for chaining.
     */
    public Builder setUnrealizedPnl(double value) {

      unrealizedPnl_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>double unrealized_pnl = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnrealizedPnl() {
      bitField0_ = (bitField0_ & ~0x00000040);
      unrealizedPnl_ = 0D;
      onChanged();
      return this;
    }

    private long lastUpdated_ ;
    /**
     * <code>int64 last_updated = 8;</code>
     * @return The lastUpdated.
     */
    @java.lang.Override
    public long getLastUpdated() {
      return lastUpdated_;
    }
    /**
     * <code>int64 last_updated = 8;</code>
     * @param value The lastUpdated to set.
     * @return This builder for chaining.
     */
    public Builder setLastUpdated(long value) {

      lastUpdated_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int64 last_updated = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastUpdated() {
      bitField0_ = (bitField0_ & ~0x00000080);
      lastUpdated_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.quantis.portfolio.GetPositionResponse)
  }

  // @@protoc_insertion_point(class_scope:com.quantis.portfolio.GetPositionResponse)
  private static final com.quantis.portfolio_service.grpc.GetPositionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.quantis.portfolio_service.grpc.GetPositionResponse();
  }

  public static com.quantis.portfolio_service.grpc.GetPositionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetPositionResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetPositionResponse>() {
    @java.lang.Override
    public GetPositionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetPositionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetPositionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.quantis.portfolio_service.grpc.GetPositionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

