// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

// Protobuf Java Version: 3.25.1
package com.quantis.portfolio_service.grpc;

/**
 * Protobuf type {@code com.quantis.portfolio.GetPortfolioValueResponse}
 */
public final class GetPortfolioValueResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.quantis.portfolio.GetPortfolioValueResponse)
    GetPortfolioValueResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetPortfolioValueResponse.newBuilder() to construct.
  private GetPortfolioValueResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetPortfolioValueResponse() {
    currency_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetPortfolioValueResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetPortfolioValueResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetPortfolioValueResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.quantis.portfolio_service.grpc.GetPortfolioValueResponse.class, com.quantis.portfolio_service.grpc.GetPortfolioValueResponse.Builder.class);
  }

  public static final int TOTAL_VALUE_FIELD_NUMBER = 1;
  private double totalValue_ = 0D;
  /**
   * <code>double total_value = 1;</code>
   * @return The totalValue.
   */
  @java.lang.Override
  public double getTotalValue() {
    return totalValue_;
  }

  public static final int CASH_BALANCE_FIELD_NUMBER = 2;
  private double cashBalance_ = 0D;
  /**
   * <code>double cash_balance = 2;</code>
   * @return The cashBalance.
   */
  @java.lang.Override
  public double getCashBalance() {
    return cashBalance_;
  }

  public static final int POSITIONS_VALUE_FIELD_NUMBER = 3;
  private double positionsValue_ = 0D;
  /**
   * <code>double positions_value = 3;</code>
   * @return The positionsValue.
   */
  @java.lang.Override
  public double getPositionsValue() {
    return positionsValue_;
  }

  public static final int UNREALIZED_PNL_FIELD_NUMBER = 4;
  private double unrealizedPnl_ = 0D;
  /**
   * <code>double unrealized_pnl = 4;</code>
   * @return The unrealizedPnl.
   */
  @java.lang.Override
  public double getUnrealizedPnl() {
    return unrealizedPnl_;
  }

  public static final int CURRENCY_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object currency_ = "";
  /**
   * <code>string currency = 5;</code>
   * @return The currency.
   */
  @java.lang.Override
  public java.lang.String getCurrency() {
    java.lang.Object ref = currency_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currency_ = s;
      return s;
    }
  }
  /**
   * <code>string currency = 5;</code>
   * @return The bytes for currency.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCurrencyBytes() {
    java.lang.Object ref = currency_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currency_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 6;
  private long timestamp_ = 0L;
  /**
   * <code>int64 timestamp = 6;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(totalValue_) != 0) {
      output.writeDouble(1, totalValue_);
    }
    if (java.lang.Double.doubleToRawLongBits(cashBalance_) != 0) {
      output.writeDouble(2, cashBalance_);
    }
    if (java.lang.Double.doubleToRawLongBits(positionsValue_) != 0) {
      output.writeDouble(3, positionsValue_);
    }
    if (java.lang.Double.doubleToRawLongBits(unrealizedPnl_) != 0) {
      output.writeDouble(4, unrealizedPnl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currency_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, currency_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(6, timestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(totalValue_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, totalValue_);
    }
    if (java.lang.Double.doubleToRawLongBits(cashBalance_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, cashBalance_);
    }
    if (java.lang.Double.doubleToRawLongBits(positionsValue_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, positionsValue_);
    }
    if (java.lang.Double.doubleToRawLongBits(unrealizedPnl_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, unrealizedPnl_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(currency_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, currency_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, timestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.quantis.portfolio_service.grpc.GetPortfolioValueResponse)) {
      return super.equals(obj);
    }
    com.quantis.portfolio_service.grpc.GetPortfolioValueResponse other = (com.quantis.portfolio_service.grpc.GetPortfolioValueResponse) obj;

    if (java.lang.Double.doubleToLongBits(getTotalValue())
        != java.lang.Double.doubleToLongBits(
            other.getTotalValue())) return false;
    if (java.lang.Double.doubleToLongBits(getCashBalance())
        != java.lang.Double.doubleToLongBits(
            other.getCashBalance())) return false;
    if (java.lang.Double.doubleToLongBits(getPositionsValue())
        != java.lang.Double.doubleToLongBits(
            other.getPositionsValue())) return false;
    if (java.lang.Double.doubleToLongBits(getUnrealizedPnl())
        != java.lang.Double.doubleToLongBits(
            other.getUnrealizedPnl())) return false;
    if (!getCurrency()
        .equals(other.getCurrency())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOTAL_VALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTotalValue()));
    hash = (37 * hash) + CASH_BALANCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCashBalance()));
    hash = (37 * hash) + POSITIONS_VALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPositionsValue()));
    hash = (37 * hash) + UNREALIZED_PNL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getUnrealizedPnl()));
    hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
    hash = (53 * hash) + getCurrency().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.quantis.portfolio_service.grpc.GetPortfolioValueResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.quantis.portfolio_service.grpc.GetPortfolioValueResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.quantis.portfolio_service.grpc.GetPortfolioValueResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.quantis.portfolio_service.grpc.GetPortfolioValueResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.quantis.portfolio_service.grpc.GetPortfolioValueResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.quantis.portfolio_service.grpc.GetPortfolioValueResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.quantis.portfolio_service.grpc.GetPortfolioValueResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.quantis.portfolio_service.grpc.GetPortfolioValueResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.quantis.portfolio_service.grpc.GetPortfolioValueResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.quantis.portfolio_service.grpc.GetPortfolioValueResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.quantis.portfolio_service.grpc.GetPortfolioValueResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.quantis.portfolio_service.grpc.GetPortfolioValueResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.quantis.portfolio_service.grpc.GetPortfolioValueResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.quantis.portfolio.GetPortfolioValueResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.quantis.portfolio.GetPortfolioValueResponse)
      com.quantis.portfolio_service.grpc.GetPortfolioValueResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetPortfolioValueResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetPortfolioValueResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.quantis.portfolio_service.grpc.GetPortfolioValueResponse.class, com.quantis.portfolio_service.grpc.GetPortfolioValueResponse.Builder.class);
    }

    // Construct using com.quantis.portfolio_service.grpc.GetPortfolioValueResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      totalValue_ = 0D;
      cashBalance_ = 0D;
      positionsValue_ = 0D;
      unrealizedPnl_ = 0D;
      currency_ = "";
      timestamp_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetPortfolioValueResponse_descriptor;
    }

    @java.lang.Override
    public com.quantis.portfolio_service.grpc.GetPortfolioValueResponse getDefaultInstanceForType() {
      return com.quantis.portfolio_service.grpc.GetPortfolioValueResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.quantis.portfolio_service.grpc.GetPortfolioValueResponse build() {
      com.quantis.portfolio_service.grpc.GetPortfolioValueResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.quantis.portfolio_service.grpc.GetPortfolioValueResponse buildPartial() {
      com.quantis.portfolio_service.grpc.GetPortfolioValueResponse result = new com.quantis.portfolio_service.grpc.GetPortfolioValueResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.quantis.portfolio_service.grpc.GetPortfolioValueResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.totalValue_ = totalValue_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.cashBalance_ = cashBalance_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.positionsValue_ = positionsValue_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.unrealizedPnl_ = unrealizedPnl_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.currency_ = currency_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.timestamp_ = timestamp_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.quantis.portfolio_service.grpc.GetPortfolioValueResponse) {
        return mergeFrom((com.quantis.portfolio_service.grpc.GetPortfolioValueResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.quantis.portfolio_service.grpc.GetPortfolioValueResponse other) {
      if (other == com.quantis.portfolio_service.grpc.GetPortfolioValueResponse.getDefaultInstance()) return this;
      if (other.getTotalValue() != 0D) {
        setTotalValue(other.getTotalValue());
      }
      if (other.getCashBalance() != 0D) {
        setCashBalance(other.getCashBalance());
      }
      if (other.getPositionsValue() != 0D) {
        setPositionsValue(other.getPositionsValue());
      }
      if (other.getUnrealizedPnl() != 0D) {
        setUnrealizedPnl(other.getUnrealizedPnl());
      }
      if (!other.getCurrency().isEmpty()) {
        currency_ = other.currency_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              totalValue_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 17: {
              cashBalance_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              positionsValue_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              unrealizedPnl_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 42: {
              currency_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double totalValue_ ;
    /**
     * <code>double total_value = 1;</code>
     * @return The totalValue.
     */
    @java.lang.Override
    public double getTotalValue() {
      return totalValue_;
    }
    /**
     * <code>double total_value = 1;</code>
     * @param value The totalValue to set.
     * @return This builder for chaining.
     */
    public Builder setTotalValue(double value) {

      totalValue_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>double total_value = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalValue() {
      bitField0_ = (bitField0_ & ~0x00000001);
      totalValue_ = 0D;
      onChanged();
      return this;
    }

    private double cashBalance_ ;
    /**
     * <code>double cash_balance = 2;</code>
     * @return The cashBalance.
     */
    @java.lang.Override
    public double getCashBalance() {
      return cashBalance_;
    }
    /**
     * <code>double cash_balance = 2;</code>
     * @param value The cashBalance to set.
     * @return This builder for chaining.
     */
    public Builder setCashBalance(double value) {

      cashBalance_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double cash_balance = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCashBalance() {
      bitField0_ = (bitField0_ & ~0x00000002);
      cashBalance_ = 0D;
      onChanged();
      return this;
    }

    private double positionsValue_ ;
    /**
     * <code>double positions_value = 3;</code>
     * @return The positionsValue.
     */
    @java.lang.Override
    public double getPositionsValue() {
      return positionsValue_;
    }
    /**
     * <code>double positions_value = 3;</code>
     * @param value The positionsValue to set.
     * @return This builder for chaining.
     */
    public Builder setPositionsValue(double value) {

      positionsValue_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double positions_value = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPositionsValue() {
      bitField0_ = (bitField0_ & ~0x00000004);
      positionsValue_ = 0D;
      onChanged();
      return this;
    }

    private double unrealizedPnl_ ;
    /**
     * <code>double unrealized_pnl = 4;</code>
     * @return The unrealizedPnl.
     */
    @java.lang.Override
    public double getUnrealizedPnl() {
      return unrealizedPnl_;
    }
    /**
     * <code>double unrealized_pnl = 4;</code>
     * @param value The unrealizedPnl to set.
     * @return This builder for chaining.
     */
    public Builder setUnrealizedPnl(double value) {

      unrealizedPnl_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>double unrealized_pnl = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnrealizedPnl() {
      bitField0_ = (bitField0_ & ~0x00000008);
      unrealizedPnl_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object currency_ = "";
    /**
     * <code>string currency = 5;</code>
     * @return The currency.
     */
    public java.lang.String getCurrency() {
      java.lang.Object ref = currency_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currency_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string currency = 5;</code>
     * @return The bytes for currency.
     */
    public com.google.protobuf.ByteString
        getCurrencyBytes() {
      java.lang.Object ref = currency_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string currency = 5;</code>
     * @param value The currency to set.
     * @return This builder for chaining.
     */
    public Builder setCurrency(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      currency_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string currency = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrency() {
      currency_ = getDefaultInstance().getCurrency();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string currency = 5;</code>
     * @param value The bytes for currency to set.
     * @return This builder for chaining.
     */
    public Builder setCurrencyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      currency_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 6;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 6;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000020);
      timestamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.quantis.portfolio.GetPortfolioValueResponse)
  }

  // @@protoc_insertion_point(class_scope:com.quantis.portfolio.GetPortfolioValueResponse)
  private static final com.quantis.portfolio_service.grpc.GetPortfolioValueResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.quantis.portfolio_service.grpc.GetPortfolioValueResponse();
  }

  public static com.quantis.portfolio_service.grpc.GetPortfolioValueResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetPortfolioValueResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetPortfolioValueResponse>() {
    @java.lang.Override
    public GetPortfolioValueResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetPortfolioValueResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetPortfolioValueResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.quantis.portfolio_service.grpc.GetPortfolioValueResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

