// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

// Protobuf Java Version: 3.25.1
package com.quantis.portfolio_service.grpc;

public interface GetPortfolioValueResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.quantis.portfolio.GetPortfolioValueResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double total_value = 1;</code>
   * @return The totalValue.
   */
  double getTotalValue();

  /**
   * <code>double cash_balance = 2;</code>
   * @return The cashBalance.
   */
  double getCashBalance();

  /**
   * <code>double positions_value = 3;</code>
   * @return The positionsValue.
   */
  double getPositionsValue();

  /**
   * <code>double unrealized_pnl = 4;</code>
   * @return The unrealizedPnl.
   */
  double getUnrealizedPnl();

  /**
   * <code>string currency = 5;</code>
   * @return The currency.
   */
  java.lang.String getCurrency();
  /**
   * <code>string currency = 5;</code>
   * @return The bytes for currency.
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();

  /**
   * <code>int64 timestamp = 6;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
