// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

// Protobuf Java Version: 3.25.1
package com.quantis.portfolio_service.grpc;

/**
 * Protobuf type {@code com.quantis.portfolio.GetTradingHistoryResponse}
 */
public final class GetTradingHistoryResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.quantis.portfolio.GetTradingHistoryResponse)
    GetTradingHistoryResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetTradingHistoryResponse.newBuilder() to construct.
  private GetTradingHistoryResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetTradingHistoryResponse() {
    trades_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetTradingHistoryResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetTradingHistoryResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetTradingHistoryResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.quantis.portfolio_service.grpc.GetTradingHistoryResponse.class, com.quantis.portfolio_service.grpc.GetTradingHistoryResponse.Builder.class);
  }

  public static final int TRADES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.quantis.portfolio_service.grpc.TradingRecord> trades_;
  /**
   * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.quantis.portfolio_service.grpc.TradingRecord> getTradesList() {
    return trades_;
  }
  /**
   * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.quantis.portfolio_service.grpc.TradingRecordOrBuilder> 
      getTradesOrBuilderList() {
    return trades_;
  }
  /**
   * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
   */
  @java.lang.Override
  public int getTradesCount() {
    return trades_.size();
  }
  /**
   * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
   */
  @java.lang.Override
  public com.quantis.portfolio_service.grpc.TradingRecord getTrades(int index) {
    return trades_.get(index);
  }
  /**
   * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
   */
  @java.lang.Override
  public com.quantis.portfolio_service.grpc.TradingRecordOrBuilder getTradesOrBuilder(
      int index) {
    return trades_.get(index);
  }

  public static final int TOTAL_COUNT_FIELD_NUMBER = 2;
  private int totalCount_ = 0;
  /**
   * <code>int32 total_count = 2;</code>
   * @return The totalCount.
   */
  @java.lang.Override
  public int getTotalCount() {
    return totalCount_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 3;
  private long timestamp_ = 0L;
  /**
   * <code>int64 timestamp = 3;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < trades_.size(); i++) {
      output.writeMessage(1, trades_.get(i));
    }
    if (totalCount_ != 0) {
      output.writeInt32(2, totalCount_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(3, timestamp_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < trades_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, trades_.get(i));
    }
    if (totalCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, totalCount_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, timestamp_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.quantis.portfolio_service.grpc.GetTradingHistoryResponse)) {
      return super.equals(obj);
    }
    com.quantis.portfolio_service.grpc.GetTradingHistoryResponse other = (com.quantis.portfolio_service.grpc.GetTradingHistoryResponse) obj;

    if (!getTradesList()
        .equals(other.getTradesList())) return false;
    if (getTotalCount()
        != other.getTotalCount()) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTradesCount() > 0) {
      hash = (37 * hash) + TRADES_FIELD_NUMBER;
      hash = (53 * hash) + getTradesList().hashCode();
    }
    hash = (37 * hash) + TOTAL_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getTotalCount();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.quantis.portfolio_service.grpc.GetTradingHistoryResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.quantis.portfolio_service.grpc.GetTradingHistoryResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.quantis.portfolio_service.grpc.GetTradingHistoryResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.quantis.portfolio_service.grpc.GetTradingHistoryResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.quantis.portfolio_service.grpc.GetTradingHistoryResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.quantis.portfolio_service.grpc.GetTradingHistoryResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.quantis.portfolio_service.grpc.GetTradingHistoryResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.quantis.portfolio_service.grpc.GetTradingHistoryResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.quantis.portfolio_service.grpc.GetTradingHistoryResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.quantis.portfolio_service.grpc.GetTradingHistoryResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.quantis.portfolio_service.grpc.GetTradingHistoryResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.quantis.portfolio_service.grpc.GetTradingHistoryResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.quantis.portfolio_service.grpc.GetTradingHistoryResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.quantis.portfolio.GetTradingHistoryResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.quantis.portfolio.GetTradingHistoryResponse)
      com.quantis.portfolio_service.grpc.GetTradingHistoryResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetTradingHistoryResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetTradingHistoryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.quantis.portfolio_service.grpc.GetTradingHistoryResponse.class, com.quantis.portfolio_service.grpc.GetTradingHistoryResponse.Builder.class);
    }

    // Construct using com.quantis.portfolio_service.grpc.GetTradingHistoryResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (tradesBuilder_ == null) {
        trades_ = java.util.Collections.emptyList();
      } else {
        trades_ = null;
        tradesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      totalCount_ = 0;
      timestamp_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.quantis.portfolio_service.grpc.PortfolioProto.internal_static_com_quantis_portfolio_GetTradingHistoryResponse_descriptor;
    }

    @java.lang.Override
    public com.quantis.portfolio_service.grpc.GetTradingHistoryResponse getDefaultInstanceForType() {
      return com.quantis.portfolio_service.grpc.GetTradingHistoryResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.quantis.portfolio_service.grpc.GetTradingHistoryResponse build() {
      com.quantis.portfolio_service.grpc.GetTradingHistoryResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.quantis.portfolio_service.grpc.GetTradingHistoryResponse buildPartial() {
      com.quantis.portfolio_service.grpc.GetTradingHistoryResponse result = new com.quantis.portfolio_service.grpc.GetTradingHistoryResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.quantis.portfolio_service.grpc.GetTradingHistoryResponse result) {
      if (tradesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          trades_ = java.util.Collections.unmodifiableList(trades_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.trades_ = trades_;
      } else {
        result.trades_ = tradesBuilder_.build();
      }
    }

    private void buildPartial0(com.quantis.portfolio_service.grpc.GetTradingHistoryResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.totalCount_ = totalCount_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.timestamp_ = timestamp_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.quantis.portfolio_service.grpc.GetTradingHistoryResponse) {
        return mergeFrom((com.quantis.portfolio_service.grpc.GetTradingHistoryResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.quantis.portfolio_service.grpc.GetTradingHistoryResponse other) {
      if (other == com.quantis.portfolio_service.grpc.GetTradingHistoryResponse.getDefaultInstance()) return this;
      if (tradesBuilder_ == null) {
        if (!other.trades_.isEmpty()) {
          if (trades_.isEmpty()) {
            trades_ = other.trades_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTradesIsMutable();
            trades_.addAll(other.trades_);
          }
          onChanged();
        }
      } else {
        if (!other.trades_.isEmpty()) {
          if (tradesBuilder_.isEmpty()) {
            tradesBuilder_.dispose();
            tradesBuilder_ = null;
            trades_ = other.trades_;
            bitField0_ = (bitField0_ & ~0x00000001);
            tradesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTradesFieldBuilder() : null;
          } else {
            tradesBuilder_.addAllMessages(other.trades_);
          }
        }
      }
      if (other.getTotalCount() != 0) {
        setTotalCount(other.getTotalCount());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.quantis.portfolio_service.grpc.TradingRecord m =
                  input.readMessage(
                      com.quantis.portfolio_service.grpc.TradingRecord.parser(),
                      extensionRegistry);
              if (tradesBuilder_ == null) {
                ensureTradesIsMutable();
                trades_.add(m);
              } else {
                tradesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16: {
              totalCount_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.quantis.portfolio_service.grpc.TradingRecord> trades_ =
      java.util.Collections.emptyList();
    private void ensureTradesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        trades_ = new java.util.ArrayList<com.quantis.portfolio_service.grpc.TradingRecord>(trades_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.quantis.portfolio_service.grpc.TradingRecord, com.quantis.portfolio_service.grpc.TradingRecord.Builder, com.quantis.portfolio_service.grpc.TradingRecordOrBuilder> tradesBuilder_;

    /**
     * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
     */
    public java.util.List<com.quantis.portfolio_service.grpc.TradingRecord> getTradesList() {
      if (tradesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(trades_);
      } else {
        return tradesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
     */
    public int getTradesCount() {
      if (tradesBuilder_ == null) {
        return trades_.size();
      } else {
        return tradesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
     */
    public com.quantis.portfolio_service.grpc.TradingRecord getTrades(int index) {
      if (tradesBuilder_ == null) {
        return trades_.get(index);
      } else {
        return tradesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
     */
    public Builder setTrades(
        int index, com.quantis.portfolio_service.grpc.TradingRecord value) {
      if (tradesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTradesIsMutable();
        trades_.set(index, value);
        onChanged();
      } else {
        tradesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
     */
    public Builder setTrades(
        int index, com.quantis.portfolio_service.grpc.TradingRecord.Builder builderForValue) {
      if (tradesBuilder_ == null) {
        ensureTradesIsMutable();
        trades_.set(index, builderForValue.build());
        onChanged();
      } else {
        tradesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
     */
    public Builder addTrades(com.quantis.portfolio_service.grpc.TradingRecord value) {
      if (tradesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTradesIsMutable();
        trades_.add(value);
        onChanged();
      } else {
        tradesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
     */
    public Builder addTrades(
        int index, com.quantis.portfolio_service.grpc.TradingRecord value) {
      if (tradesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTradesIsMutable();
        trades_.add(index, value);
        onChanged();
      } else {
        tradesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
     */
    public Builder addTrades(
        com.quantis.portfolio_service.grpc.TradingRecord.Builder builderForValue) {
      if (tradesBuilder_ == null) {
        ensureTradesIsMutable();
        trades_.add(builderForValue.build());
        onChanged();
      } else {
        tradesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
     */
    public Builder addTrades(
        int index, com.quantis.portfolio_service.grpc.TradingRecord.Builder builderForValue) {
      if (tradesBuilder_ == null) {
        ensureTradesIsMutable();
        trades_.add(index, builderForValue.build());
        onChanged();
      } else {
        tradesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
     */
    public Builder addAllTrades(
        java.lang.Iterable<? extends com.quantis.portfolio_service.grpc.TradingRecord> values) {
      if (tradesBuilder_ == null) {
        ensureTradesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, trades_);
        onChanged();
      } else {
        tradesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
     */
    public Builder clearTrades() {
      if (tradesBuilder_ == null) {
        trades_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        tradesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
     */
    public Builder removeTrades(int index) {
      if (tradesBuilder_ == null) {
        ensureTradesIsMutable();
        trades_.remove(index);
        onChanged();
      } else {
        tradesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
     */
    public com.quantis.portfolio_service.grpc.TradingRecord.Builder getTradesBuilder(
        int index) {
      return getTradesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
     */
    public com.quantis.portfolio_service.grpc.TradingRecordOrBuilder getTradesOrBuilder(
        int index) {
      if (tradesBuilder_ == null) {
        return trades_.get(index);  } else {
        return tradesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
     */
    public java.util.List<? extends com.quantis.portfolio_service.grpc.TradingRecordOrBuilder> 
         getTradesOrBuilderList() {
      if (tradesBuilder_ != null) {
        return tradesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(trades_);
      }
    }
    /**
     * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
     */
    public com.quantis.portfolio_service.grpc.TradingRecord.Builder addTradesBuilder() {
      return getTradesFieldBuilder().addBuilder(
          com.quantis.portfolio_service.grpc.TradingRecord.getDefaultInstance());
    }
    /**
     * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
     */
    public com.quantis.portfolio_service.grpc.TradingRecord.Builder addTradesBuilder(
        int index) {
      return getTradesFieldBuilder().addBuilder(
          index, com.quantis.portfolio_service.grpc.TradingRecord.getDefaultInstance());
    }
    /**
     * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
     */
    public java.util.List<com.quantis.portfolio_service.grpc.TradingRecord.Builder> 
         getTradesBuilderList() {
      return getTradesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.quantis.portfolio_service.grpc.TradingRecord, com.quantis.portfolio_service.grpc.TradingRecord.Builder, com.quantis.portfolio_service.grpc.TradingRecordOrBuilder> 
        getTradesFieldBuilder() {
      if (tradesBuilder_ == null) {
        tradesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.quantis.portfolio_service.grpc.TradingRecord, com.quantis.portfolio_service.grpc.TradingRecord.Builder, com.quantis.portfolio_service.grpc.TradingRecordOrBuilder>(
                trades_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        trades_ = null;
      }
      return tradesBuilder_;
    }

    private int totalCount_ ;
    /**
     * <code>int32 total_count = 2;</code>
     * @return The totalCount.
     */
    @java.lang.Override
    public int getTotalCount() {
      return totalCount_;
    }
    /**
     * <code>int32 total_count = 2;</code>
     * @param value The totalCount to set.
     * @return This builder for chaining.
     */
    public Builder setTotalCount(int value) {

      totalCount_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 total_count = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalCount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      totalCount_ = 0;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 3;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 3;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000004);
      timestamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.quantis.portfolio.GetTradingHistoryResponse)
  }

  // @@protoc_insertion_point(class_scope:com.quantis.portfolio.GetTradingHistoryResponse)
  private static final com.quantis.portfolio_service.grpc.GetTradingHistoryResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.quantis.portfolio_service.grpc.GetTradingHistoryResponse();
  }

  public static com.quantis.portfolio_service.grpc.GetTradingHistoryResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetTradingHistoryResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetTradingHistoryResponse>() {
    @java.lang.Override
    public GetTradingHistoryResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetTradingHistoryResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetTradingHistoryResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.quantis.portfolio_service.grpc.GetTradingHistoryResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

