// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

// Protobuf Java Version: 3.25.1
package com.quantis.portfolio_service.grpc;

public interface GetTradingHistoryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.quantis.portfolio.GetTradingHistoryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
   */
  java.util.List<com.quantis.portfolio_service.grpc.TradingRecord> 
      getTradesList();
  /**
   * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
   */
  com.quantis.portfolio_service.grpc.TradingRecord getTrades(int index);
  /**
   * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
   */
  int getTradesCount();
  /**
   * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
   */
  java.util.List<? extends com.quantis.portfolio_service.grpc.TradingRecordOrBuilder> 
      getTradesOrBuilderList();
  /**
   * <code>repeated .com.quantis.portfolio.TradingRecord trades = 1;</code>
   */
  com.quantis.portfolio_service.grpc.TradingRecordOrBuilder getTradesOrBuilder(
      int index);

  /**
   * <code>int32 total_count = 2;</code>
   * @return The totalCount.
   */
  int getTotalCount();

  /**
   * <code>int64 timestamp = 3;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
