// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

// Protobuf Java Version: 3.25.1
package com.quantis.portfolio_service.grpc;

public final class PortfolioProto {
  private PortfolioProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quantis_portfolio_GetCashBalanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quantis_portfolio_GetCashBalanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quantis_portfolio_GetCashBalanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quantis_portfolio_GetCashBalanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quantis_portfolio_GetPositionValueRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quantis_portfolio_GetPositionValueRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quantis_portfolio_GetPositionValueResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quantis_portfolio_GetPositionValueResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quantis_portfolio_GetPortfolioValueRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quantis_portfolio_GetPortfolioValueRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quantis_portfolio_GetPortfolioValueResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quantis_portfolio_GetPortfolioValueResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quantis_portfolio_GetPositionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quantis_portfolio_GetPositionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quantis_portfolio_GetPositionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quantis_portfolio_GetPositionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quantis_portfolio_GetAllPositionsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quantis_portfolio_GetAllPositionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quantis_portfolio_GetAllPositionsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quantis_portfolio_GetAllPositionsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quantis_portfolio_UpdatePositionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quantis_portfolio_UpdatePositionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quantis_portfolio_UpdatePositionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quantis_portfolio_UpdatePositionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quantis_portfolio_GetTradingHistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quantis_portfolio_GetTradingHistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quantis_portfolio_TradingRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quantis_portfolio_TradingRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_quantis_portfolio_GetTradingHistoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_quantis_portfolio_GetTradingHistoryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017portfolio.proto\022\025com.quantis.portfolio" +
      "\"(\n\025GetCashBalanceRequest\022\017\n\007user_id\030\001 \001" +
      "(\t\"S\n\026GetCashBalanceResponse\022\024\n\014cash_bal" +
      "ance\030\001 \001(\001\022\020\n\010currency\030\002 \001(\t\022\021\n\ttimestam" +
      "p\030\003 \001(\003\":\n\027GetPositionValueRequest\022\017\n\007us" +
      "er_id\030\001 \001(\t\022\016\n\006symbol\030\002 \001(\t\"\255\001\n\030GetPosit" +
      "ionValueResponse\022\026\n\016position_value\030\001 \001(\001" +
      "\022\020\n\010quantity\030\002 \001(\001\022\025\n\raverage_price\030\003 \001(" +
      "\001\022\025\n\rcurrent_price\030\004 \001(\001\022\026\n\016unrealized_p" +
      "nl\030\005 \001(\001\022\016\n\006symbol\030\006 \001(\t\022\021\n\ttimestamp\030\007 " +
      "\001(\003\"+\n\030GetPortfolioValueRequest\022\017\n\007user_" +
      "id\030\001 \001(\t\"\234\001\n\031GetPortfolioValueResponse\022\023" +
      "\n\013total_value\030\001 \001(\001\022\024\n\014cash_balance\030\002 \001(" +
      "\001\022\027\n\017positions_value\030\003 \001(\001\022\026\n\016unrealized" +
      "_pnl\030\004 \001(\001\022\020\n\010currency\030\005 \001(\t\022\021\n\ttimestam" +
      "p\030\006 \001(\003\"5\n\022GetPositionRequest\022\017\n\007user_id" +
      "\030\001 \001(\t\022\016\n\006symbol\030\002 \001(\t\"\272\001\n\023GetPositionRe" +
      "sponse\022\017\n\007user_id\030\001 \001(\t\022\016\n\006symbol\030\002 \001(\t\022" +
      "\020\n\010quantity\030\003 \001(\001\022\025\n\raverage_price\030\004 \001(\001" +
      "\022\025\n\rcurrent_price\030\005 \001(\001\022\024\n\014market_value\030" +
      "\006 \001(\001\022\026\n\016unrealized_pnl\030\007 \001(\001\022\024\n\014last_up" +
      "dated\030\010 \001(\003\")\n\026GetAllPositionsRequest\022\017\n" +
      "\007user_id\030\001 \001(\t\"\250\001\n\027GetAllPositionsRespon" +
      "se\022=\n\tpositions\030\001 \003(\0132*.com.quantis.port" +
      "folio.GetPositionResponse\022\035\n\025total_posit" +
      "ions_value\030\002 \001(\001\022\034\n\024total_unrealized_pnl" +
      "\030\003 \001(\001\022\021\n\ttimestamp\030\004 \001(\003\"\200\001\n\025UpdatePosi" +
      "tionRequest\022\017\n\007user_id\030\001 \001(\t\022\016\n\006symbol\030\002" +
      " \001(\t\022\027\n\017quantity_change\030\003 \001(\001\022\r\n\005price\030\004" +
      " \001(\001\022\014\n\004side\030\005 \001(\t\022\020\n\010order_id\030\006 \001(\t\"\200\001\n" +
      "\026UpdatePositionResponse\022\017\n\007success\030\001 \001(\010" +
      "\022\017\n\007message\030\002 \001(\t\022D\n\020updated_position\030\003 " +
      "\001(\0132*.com.quantis.portfolio.GetPositionR" +
      "esponse\"j\n\030GetTradingHistoryRequest\022\017\n\007u" +
      "ser_id\030\001 \001(\t\022\r\n\005limit\030\002 \001(\005\022\027\n\017start_tim" +
      "estamp\030\003 \001(\003\022\025\n\rend_timestamp\030\004 \001(\003\"\230\001\n\r" +
      "TradingRecord\022\020\n\010order_id\030\001 \001(\t\022\016\n\006symbo" +
      "l\030\002 \001(\t\022\014\n\004side\030\003 \001(\t\022\020\n\010quantity\030\004 \001(\001\022" +
      "\r\n\005price\030\005 \001(\001\022\023\n\013total_value\030\006 \001(\001\022\021\n\tt" +
      "imestamp\030\007 \001(\003\022\016\n\006status\030\010 \001(\t\"y\n\031GetTra" +
      "dingHistoryResponse\0224\n\006trades\030\001 \003(\0132$.co" +
      "m.quantis.portfolio.TradingRecord\022\023\n\013tot" +
      "al_count\030\002 \001(\005\022\021\n\ttimestamp\030\003 \001(\0032\255\006\n\020Po" +
      "rtfolioService\022m\n\016GetCashBalance\022,.com.q" +
      "uantis.portfolio.GetCashBalanceRequest\032-" +
      ".com.quantis.portfolio.GetCashBalanceRes" +
      "ponse\022s\n\020GetPositionValue\022..com.quantis." +
      "portfolio.GetPositionValueRequest\032/.com." +
      "quantis.portfolio.GetPositionValueRespon" +
      "se\022v\n\021GetPortfolioValue\022/.com.quantis.po" +
      "rtfolio.GetPortfolioValueRequest\0320.com.q" +
      "uantis.portfolio.GetPortfolioValueRespon" +
      "se\022d\n\013GetPosition\022).com.quantis.portfoli" +
      "o.GetPositionRequest\032*.com.quantis.portf" +
      "olio.GetPositionResponse\022p\n\017GetAllPositi" +
      "ons\022-.com.quantis.portfolio.GetAllPositi" +
      "onsRequest\032..com.quantis.portfolio.GetAl" +
      "lPositionsResponse\022m\n\016UpdatePosition\022,.c" +
      "om.quantis.portfolio.UpdatePositionReque" +
      "st\032-.com.quantis.portfolio.UpdatePositio" +
      "nResponse\022v\n\021GetTradingHistory\022/.com.qua" +
      "ntis.portfolio.GetTradingHistoryRequest\032" +
      "0.com.quantis.portfolio.GetTradingHistor" +
      "yResponseB6\n\"com.quantis.portfolio_servi" +
      "ce.grpcB\016PortfolioProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_quantis_portfolio_GetCashBalanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_quantis_portfolio_GetCashBalanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quantis_portfolio_GetCashBalanceRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_com_quantis_portfolio_GetCashBalanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_quantis_portfolio_GetCashBalanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quantis_portfolio_GetCashBalanceResponse_descriptor,
        new java.lang.String[] { "CashBalance", "Currency", "Timestamp", });
    internal_static_com_quantis_portfolio_GetPositionValueRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_quantis_portfolio_GetPositionValueRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quantis_portfolio_GetPositionValueRequest_descriptor,
        new java.lang.String[] { "UserId", "Symbol", });
    internal_static_com_quantis_portfolio_GetPositionValueResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_quantis_portfolio_GetPositionValueResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quantis_portfolio_GetPositionValueResponse_descriptor,
        new java.lang.String[] { "PositionValue", "Quantity", "AveragePrice", "CurrentPrice", "UnrealizedPnl", "Symbol", "Timestamp", });
    internal_static_com_quantis_portfolio_GetPortfolioValueRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_quantis_portfolio_GetPortfolioValueRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quantis_portfolio_GetPortfolioValueRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_com_quantis_portfolio_GetPortfolioValueResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_quantis_portfolio_GetPortfolioValueResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quantis_portfolio_GetPortfolioValueResponse_descriptor,
        new java.lang.String[] { "TotalValue", "CashBalance", "PositionsValue", "UnrealizedPnl", "Currency", "Timestamp", });
    internal_static_com_quantis_portfolio_GetPositionRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_quantis_portfolio_GetPositionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quantis_portfolio_GetPositionRequest_descriptor,
        new java.lang.String[] { "UserId", "Symbol", });
    internal_static_com_quantis_portfolio_GetPositionResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_quantis_portfolio_GetPositionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quantis_portfolio_GetPositionResponse_descriptor,
        new java.lang.String[] { "UserId", "Symbol", "Quantity", "AveragePrice", "CurrentPrice", "MarketValue", "UnrealizedPnl", "LastUpdated", });
    internal_static_com_quantis_portfolio_GetAllPositionsRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_quantis_portfolio_GetAllPositionsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quantis_portfolio_GetAllPositionsRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_com_quantis_portfolio_GetAllPositionsResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_quantis_portfolio_GetAllPositionsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quantis_portfolio_GetAllPositionsResponse_descriptor,
        new java.lang.String[] { "Positions", "TotalPositionsValue", "TotalUnrealizedPnl", "Timestamp", });
    internal_static_com_quantis_portfolio_UpdatePositionRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_quantis_portfolio_UpdatePositionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quantis_portfolio_UpdatePositionRequest_descriptor,
        new java.lang.String[] { "UserId", "Symbol", "QuantityChange", "Price", "Side", "OrderId", });
    internal_static_com_quantis_portfolio_UpdatePositionResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_quantis_portfolio_UpdatePositionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quantis_portfolio_UpdatePositionResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "UpdatedPosition", });
    internal_static_com_quantis_portfolio_GetTradingHistoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_quantis_portfolio_GetTradingHistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quantis_portfolio_GetTradingHistoryRequest_descriptor,
        new java.lang.String[] { "UserId", "Limit", "StartTimestamp", "EndTimestamp", });
    internal_static_com_quantis_portfolio_TradingRecord_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_quantis_portfolio_TradingRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quantis_portfolio_TradingRecord_descriptor,
        new java.lang.String[] { "OrderId", "Symbol", "Side", "Quantity", "Price", "TotalValue", "Timestamp", "Status", });
    internal_static_com_quantis_portfolio_GetTradingHistoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_quantis_portfolio_GetTradingHistoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_quantis_portfolio_GetTradingHistoryResponse_descriptor,
        new java.lang.String[] { "Trades", "TotalCount", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
